import Tab from '@components/tabs/Tab';
import Tabs from '@components/tabs/Tabs';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';

const Home: NextPage = () => {
  const router = useRouter();
  const [selectedTab, setSelectedTab] = useState('all');
  const handleChange = (text: string) => {
    setSelectedTab(text);
    router.push(text);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        main 메이지
        <Tabs text={selectedTab} onChange={handleChange}>
          <Tab text={'all'}>모임 전체</Tab>
          <Tab text={'mine'}>내 모임</Tab>
        </Tabs>
      </main>
    </div>
  );
};

export default Home;
